server:
  port: 8888

cors:
  originPatterns: http://localhost:8080,http://localhost:3000,https://www.instagram.com

file:
  upload-dir: /Documentos/projetos/spring/spring_course/uploadDir

spring:
  application:
    name: spring-course

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    show-sql: true
    open-in-view: false

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215 MB


logging:
  level:
    # root: WARN
    br.com.sobreiraromulo: DEBUG

spring-doc:
  paths-to-match: /api/**/v1/**
  swagger-ui:
    use-root-path: true